name: MineHunt
version: '${project.version}'
main: net.mcxk.minehunt.MineHunt
api-version: 1.16
soft-depend: [ NoteBlockAPI, AdvancedReplay, PlaceholderAPI ]
commands:
  minehunt:
    description: 猎人游戏指令
    usage: /<command> [copyright|hunter|runner|resetcountdown|players|forcestart|want|prepare]


