# 本插件版本为MossCG瞎改改出来的
# 原本是给MossMC群组单独修改的但是想了想就发布开源了
# 欢迎来墨守的群里反馈bug：779291908
# 一般会在2天内修复（除非我懒）
# 下面是插件配置文件www~

#本局最大玩家数
max-players: 16

#本局最小玩家数（不达到这个数量不会开局）
min-players: 2

#本局最大Runner数（这东西我基本用不到了但是还是不敢删免得出问题）
runner-max: 2

#第零阶梯玩家数量（大于等于该数量Runner会设置对应阶梯数量，下同）
#如L0Player=2 L0Hunter=1即在总玩家达到2及以上的时候，猎人数为1）
L0Player: 2

#第零阶梯猎人数量
L0Hunter: 1

#第一阶梯玩家数量
L1Player: 6

#第一阶梯猎人数量
L1Hunter: 2

#第二阶梯玩家数量
L2Player: 12

#第二阶梯猎人数量
L2Hunter: 3

#第三阶梯玩家数量
L3Player: 16

#第三阶梯猎人数量
L3Hunter: 4

#是否开局解锁指南针
CompassUnlocked: true

#服务器名称（实际上也就结束统计的时候显示一下）
ServerName: "MossMC"

#游戏名称（实际上也同样就结束统计的时候显示一下）
ServerGame: "猎人游戏"

#观战玩家名字前缀
ObserverName: "[吃瓜]"

#追杀者玩家名字前缀
HunterName: "[猎人]"

#逃亡者玩家名字前缀
RunnerName: "[逃亡者]"

#统计展示的击杀龙的玩家
DragonKiller: "屠龙勇士"

#统计展示的击杀逃亡者的玩家
RunnerKiller: "最佳猎人"

#统计展示的对任何实体输出伤害最多的玩家
DamageOutPut: "最佳输出"

#统计展示的受到伤害最多的玩家
DamageReceive: "最惨靶子"

#统计展示的对队友输出最多的玩家
TeamKiller: "队友杀手"

#统计展示的移动距离最多的玩家
WalkMaster: "大旅行者"

#统计展示的跳跃次数最多的玩家
JumpMaster: "蹦迪大师"

#统计展示结束后的结语
EndText1: "感谢游玩"
EndText2: "Thanks for playing!"