name: MineHunt
version: 2.1.1
main: net.mcxk.minehunt.MineHunt
api-version: 1.16
soft-depend: [ NoteBlockAPI, AdvancedReplay ]
commands:
  minehunt:
    description: 作者懒得写，我也懒得写，自己去看简介去~
    usage: 你猜咋用